type_name:
  allowed_symbols: "_"

identifier_name:
  allowed_symbols: "_"
  
disabled_rules: # rule identifiers to exclude from running
  # - colon
  - comma
  # - control_statement
  - variable_name
  - large_tuple
  - notification_center_detachment
  - nesting
  - function_parameter_count
  - trailing_whitespace
  
opt_in_rules: # some rules are only opt-in
  - empty_count
